[project]
name = "tawala-gov"
version = "0.1.0"
description = "Python SDK for Tawala.ai"
authors = [
  { name = "Tawala dev team", email = "info@tawala.ai" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "requests",
  "pydantic",
  "hatch>=1.16.5",
]
license = { file = "LICENSE.md" }

classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
"Homepage" = "https://github.com/tawalai/tawala"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
where = ["src/tawala"]
